version: "3.8"

services:
  backend:
    command: npm run dev
    build:
      context: ./backend
    container_name: pokeapi-backend
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    tty: true
