version: "3.8"

services:
  backend:
    build:
      context: ./backend
    container_name: pokeapi-backend
    command: npm run dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    tty: true

  frontend:
    build:
      context: ./frontend
    container_name: pokeapi-frontend
    command: npm run dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    tty: true
    environment:
      - VITE_API_URL=http://localhost:3001
